unitb-config revamp (#34)
Swap out ConfigFile for yaml

* [1/4] Swap out ConfigFile for yaml
Config file's name changed from z3_config.conf to z3_config.yml.

TODO: there's a slight issue with the yaml library treating all
of Z3Config's fields as String, in that it will require the numbers
to be explicitly quoted to be considered as string literals; and
otherwise it will ignore them. We'll try to fix this by generalizing
the Document type class and the functions using it.

* [2/4][WIP] Generalize Document

* [3/4] Generalize Document (cleanup)

- literate-unitb-config compiles again
- Add traverseOf (similar to lensOf and prismOf)
- Swap `fieldWith`'s arguments to make them consistent with `field`

* [4/4] Rename unitb-option executable to unitb-config

* Pin yaml to >= 0.8.22 to avoid issue with STM

yaml < 0.8.22 causes literate-unitb-logic's test suite to throw an
exception: Control.Concurrent.STM.atomically was nested

Possibly related: https://github.com/snoyberg/yaml/issues/86

Not sure about the exact cause, but we don't seem to have the issue
with yaml >= 0.8.22, so I'm bumping the lower bound as a workaround.

* Clean up comments

* Align =>, ->, and :: properly