Pin yaml to >= 0.8.22 to avoid issue with STM
yaml < 0.8.22 causes literate-unitb-logic's test suite to throw an
exception: Control.Concurrent.STM.atomically was nested

Possibly related: https://github.com/snoyberg/yaml/issues/86

Not sure about the exact cause, but we don't seem to have the issue
with yaml >= 0.8.22, so I'm bumping the lower bound as a workaround.